server:
  port: 8081

spring:
  #  数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 10000
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 3000
      connection-test-query: SELECT 1

  redis:
    connect-timeout: 10000ms
    #服务器地址
    host: 192.168.72.136
    port: 6379
    #数据库
    database: 0
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.xxxx.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

logging:
  level:
    com.xxxx.server.mapper: debug

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: yeb-secret
  # Jwt 的超期限时间（60*60）*24
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer


